### ISSUE TITLE
canvas mode / floating panels

### ISSUE THREAD

**Issue by edenvidal** [weareunderdesign/rnbw#868]
- [x] Position issue: The design view should be on canvas center. let's remove the functionality to scroll top/left/right/bottom (it was an experiment. if it made correctly, so when resizing either from right/left-top/down, the page would always keep itself at the center.
- [x] Zoom issue: When zooming the canvas, when the Iframe (design view) changes to a container under the cursor, the entire page scales unexpectedly. (Maybe its happens because IFrame, but I not find the issue resolving).
- [x] sometimes the page is getting marked as selected content, we'll need to make it impossible for the canvas container.
- [x] When zoom in, the design becomes larger than the canvas, part of the design page goes beyond the canvas container and we can't access it with the scroll.
- [x] add size indication (width/height)
- [x] add design and information to rnbw.design/guide

**Comment by stanislavasal** [comment]
@edenvidal Hello! Can you show me these problems tomorrow on the call please? (I saw you invited me) For me it's a little bit hard to understand them without seeing
